version: '2'
services:
  web:
    image: apiserver
    ports:
     - "3000:3000"
     - "4000:4000"
    # mount project directory to code directory on container
    volumes:
     - .:/code
    depends_on:
      - db
    command: pg_ctl -D /var/lib/postgresql/data -l logfile start && npm start
  db:
    image: postgres
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    command: /docker-entrypoint.sh postgres
